package org.yaukie.frame.autocode.model;

import java.io.Serializable;

public class XDict implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_dict.id
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_dict.dict_name
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_dict.dict_id
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    private String dictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_dict.dict_key
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    private String dictKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_dict.dict_value
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    private String dictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_dict.order_num
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_dict.dict_desc
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    private String dictDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_dict.id
     *
     * @return the value of x_dict.id
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_dict.id
     *
     * @param id the value for x_dict.id
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_dict.dict_name
     *
     * @return the value of x_dict.dict_name
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_dict.dict_name
     *
     * @param dictName the value for x_dict.dict_name
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public void setDictName(String dictName) {
        this.dictName = dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_dict.dict_id
     *
     * @return the value of x_dict.dict_id
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public String getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_dict.dict_id
     *
     * @param dictId the value for x_dict.dict_id
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public void setDictId(String dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_dict.dict_key
     *
     * @return the value of x_dict.dict_key
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public String getDictKey() {
        return dictKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_dict.dict_key
     *
     * @param dictKey the value for x_dict.dict_key
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public void setDictKey(String dictKey) {
        this.dictKey = dictKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_dict.dict_value
     *
     * @return the value of x_dict.dict_value
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_dict.dict_value
     *
     * @param dictValue the value for x_dict.dict_value
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_dict.order_num
     *
     * @return the value of x_dict.order_num
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_dict.order_num
     *
     * @param orderNum the value for x_dict.order_num
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_dict.dict_desc
     *
     * @return the value of x_dict.dict_desc
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public String getDictDesc() {
        return dictDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_dict.dict_desc
     *
     * @param dictDesc the value for x_dict.dict_desc
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    public void setDictDesc(String dictDesc) {
        this.dictDesc = dictDesc;
    }
}