package org.yaukie.frame.autocode.model;

import java.io.Serializable;
import java.util.Date;

public class XLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log.id
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log.log_id
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private String logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log.target_id
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private String targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log.log_type
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private String logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log.log_file_path
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private String logFilePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log.start_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log.stop_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private String stopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log.created_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log.update_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log.target_result
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private String targetResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log.log_text
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private String logText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log.id
     *
     * @return the value of x_log.id
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log.id
     *
     * @param id the value for x_log.id
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log.log_id
     *
     * @return the value of x_log.log_id
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log.log_id
     *
     * @param logId the value for x_log.log_id
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public void setLogId(String logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log.target_id
     *
     * @return the value of x_log.target_id
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log.target_id
     *
     * @param targetId the value for x_log.target_id
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log.log_type
     *
     * @return the value of x_log.log_type
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log.log_type
     *
     * @param logType the value for x_log.log_type
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public void setLogType(String logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log.log_file_path
     *
     * @return the value of x_log.log_file_path
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public String getLogFilePath() {
        return logFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log.log_file_path
     *
     * @param logFilePath the value for x_log.log_file_path
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public void setLogFilePath(String logFilePath) {
        this.logFilePath = logFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log.start_time
     *
     * @return the value of x_log.start_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log.start_time
     *
     * @param startTime the value for x_log.start_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log.stop_time
     *
     * @return the value of x_log.stop_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public String getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log.stop_time
     *
     * @param stopTime the value for x_log.stop_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public void setStopTime(String stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log.created_time
     *
     * @return the value of x_log.created_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log.created_time
     *
     * @param createdTime the value for x_log.created_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log.update_time
     *
     * @return the value of x_log.update_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log.update_time
     *
     * @param updateTime the value for x_log.update_time
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log.target_result
     *
     * @return the value of x_log.target_result
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public String getTargetResult() {
        return targetResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log.target_result
     *
     * @param targetResult the value for x_log.target_result
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public void setTargetResult(String targetResult) {
        this.targetResult = targetResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log.log_text
     *
     * @return the value of x_log.log_text
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public String getLogText() {
        return logText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log.log_text
     *
     * @param logText the value for x_log.log_text
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    public void setLogText(String logText) {
        this.logText = logText;
    }
}