package org.yaukie.frame.autocode.model;

import java.io.Serializable;
import java.util.Date;

public class XLogWarning implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.id
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.log_id
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private String logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.target_id
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private String targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.target_name
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private String targetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.log_type
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private String logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.log_file
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private String logFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.log_level
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private String logLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.log_error
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private String logError;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.log_subject
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private String logSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.created_time
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.update_time
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_log_warning.log_msg
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private String logMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.id
     *
     * @return the value of x_log_warning.id
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.id
     *
     * @param id the value for x_log_warning.id
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.log_id
     *
     * @return the value of x_log_warning.log_id
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.log_id
     *
     * @param logId the value for x_log_warning.log_id
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setLogId(String logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.target_id
     *
     * @return the value of x_log_warning.target_id
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.target_id
     *
     * @param targetId the value for x_log_warning.target_id
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.target_name
     *
     * @return the value of x_log_warning.target_name
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.target_name
     *
     * @param targetName the value for x_log_warning.target_name
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.log_type
     *
     * @return the value of x_log_warning.log_type
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.log_type
     *
     * @param logType the value for x_log_warning.log_type
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setLogType(String logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.log_file
     *
     * @return the value of x_log_warning.log_file
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public String getLogFile() {
        return logFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.log_file
     *
     * @param logFile the value for x_log_warning.log_file
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setLogFile(String logFile) {
        this.logFile = logFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.log_level
     *
     * @return the value of x_log_warning.log_level
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public String getLogLevel() {
        return logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.log_level
     *
     * @param logLevel the value for x_log_warning.log_level
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setLogLevel(String logLevel) {
        this.logLevel = logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.log_error
     *
     * @return the value of x_log_warning.log_error
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public String getLogError() {
        return logError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.log_error
     *
     * @param logError the value for x_log_warning.log_error
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setLogError(String logError) {
        this.logError = logError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.log_subject
     *
     * @return the value of x_log_warning.log_subject
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public String getLogSubject() {
        return logSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.log_subject
     *
     * @param logSubject the value for x_log_warning.log_subject
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setLogSubject(String logSubject) {
        this.logSubject = logSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.created_time
     *
     * @return the value of x_log_warning.created_time
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.created_time
     *
     * @param createdTime the value for x_log_warning.created_time
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.update_time
     *
     * @return the value of x_log_warning.update_time
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.update_time
     *
     * @param updateTime the value for x_log_warning.update_time
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_log_warning.log_msg
     *
     * @return the value of x_log_warning.log_msg
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public String getLogMsg() {
        return logMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_log_warning.log_msg
     *
     * @param logMsg the value for x_log_warning.log_msg
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    public void setLogMsg(String logMsg) {
        this.logMsg = logMsg;
    }
}