package org.yaukie.frame.autocode.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XMonitorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public XMonitorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMonitorIdIsNull() {
            addCriterion("monitor_id is null");
            return (Criteria) this;
        }

        public Criteria andMonitorIdIsNotNull() {
            addCriterion("monitor_id is not null");
            return (Criteria) this;
        }

        public Criteria andMonitorIdEqualTo(String value) {
            addCriterion("monitor_id =", value, "monitorId");
            return (Criteria) this;
        }

        public Criteria andMonitorIdNotEqualTo(String value) {
            addCriterion("monitor_id <>", value, "monitorId");
            return (Criteria) this;
        }

        public Criteria andMonitorIdGreaterThan(String value) {
            addCriterion("monitor_id >", value, "monitorId");
            return (Criteria) this;
        }

        public Criteria andMonitorIdGreaterThanOrEqualTo(String value) {
            addCriterion("monitor_id >=", value, "monitorId");
            return (Criteria) this;
        }

        public Criteria andMonitorIdLessThan(String value) {
            addCriterion("monitor_id <", value, "monitorId");
            return (Criteria) this;
        }

        public Criteria andMonitorIdLessThanOrEqualTo(String value) {
            addCriterion("monitor_id <=", value, "monitorId");
            return (Criteria) this;
        }

        public Criteria andMonitorIdLike(String value) {
            addCriterion("monitor_id like", value, "monitorId");
            return (Criteria) this;
        }

        public Criteria andMonitorIdNotLike(String value) {
            addCriterion("monitor_id not like", value, "monitorId");
            return (Criteria) this;
        }

        public Criteria andMonitorIdIn(List<String> values) {
            addCriterion("monitor_id in", values, "monitorId");
            return (Criteria) this;
        }

        public Criteria andMonitorIdNotIn(List<String> values) {
            addCriterion("monitor_id not in", values, "monitorId");
            return (Criteria) this;
        }

        public Criteria andMonitorIdBetween(String value1, String value2) {
            addCriterion("monitor_id between", value1, value2, "monitorId");
            return (Criteria) this;
        }

        public Criteria andMonitorIdNotBetween(String value1, String value2) {
            addCriterion("monitor_id not between", value1, value2, "monitorId");
            return (Criteria) this;
        }

        public Criteria andTargetIdIsNull() {
            addCriterion("target_id is null");
            return (Criteria) this;
        }

        public Criteria andTargetIdIsNotNull() {
            addCriterion("target_id is not null");
            return (Criteria) this;
        }

        public Criteria andTargetIdEqualTo(String value) {
            addCriterion("target_id =", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotEqualTo(String value) {
            addCriterion("target_id <>", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThan(String value) {
            addCriterion("target_id >", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThanOrEqualTo(String value) {
            addCriterion("target_id >=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThan(String value) {
            addCriterion("target_id <", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThanOrEqualTo(String value) {
            addCriterion("target_id <=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLike(String value) {
            addCriterion("target_id like", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotLike(String value) {
            addCriterion("target_id not like", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdIn(List<String> values) {
            addCriterion("target_id in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotIn(List<String> values) {
            addCriterion("target_id not in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdBetween(String value1, String value2) {
            addCriterion("target_id between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotBetween(String value1, String value2) {
            addCriterion("target_id not between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andSuccessCountIsNull() {
            addCriterion("success_count is null");
            return (Criteria) this;
        }

        public Criteria andSuccessCountIsNotNull() {
            addCriterion("success_count is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessCountEqualTo(String value) {
            addCriterion("success_count =", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountNotEqualTo(String value) {
            addCriterion("success_count <>", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountGreaterThan(String value) {
            addCriterion("success_count >", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountGreaterThanOrEqualTo(String value) {
            addCriterion("success_count >=", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountLessThan(String value) {
            addCriterion("success_count <", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountLessThanOrEqualTo(String value) {
            addCriterion("success_count <=", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountLike(String value) {
            addCriterion("success_count like", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountNotLike(String value) {
            addCriterion("success_count not like", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountIn(List<String> values) {
            addCriterion("success_count in", values, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountNotIn(List<String> values) {
            addCriterion("success_count not in", values, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountBetween(String value1, String value2) {
            addCriterion("success_count between", value1, value2, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountNotBetween(String value1, String value2) {
            addCriterion("success_count not between", value1, value2, "successCount");
            return (Criteria) this;
        }

        public Criteria andFailCountIsNull() {
            addCriterion("fail_count is null");
            return (Criteria) this;
        }

        public Criteria andFailCountIsNotNull() {
            addCriterion("fail_count is not null");
            return (Criteria) this;
        }

        public Criteria andFailCountEqualTo(String value) {
            addCriterion("fail_count =", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountNotEqualTo(String value) {
            addCriterion("fail_count <>", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountGreaterThan(String value) {
            addCriterion("fail_count >", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountGreaterThanOrEqualTo(String value) {
            addCriterion("fail_count >=", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountLessThan(String value) {
            addCriterion("fail_count <", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountLessThanOrEqualTo(String value) {
            addCriterion("fail_count <=", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountLike(String value) {
            addCriterion("fail_count like", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountNotLike(String value) {
            addCriterion("fail_count not like", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountIn(List<String> values) {
            addCriterion("fail_count in", values, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountNotIn(List<String> values) {
            addCriterion("fail_count not in", values, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountBetween(String value1, String value2) {
            addCriterion("fail_count between", value1, value2, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountNotBetween(String value1, String value2) {
            addCriterion("fail_count not between", value1, value2, "failCount");
            return (Criteria) this;
        }

        public Criteria andTargetStatusIsNull() {
            addCriterion("target_status is null");
            return (Criteria) this;
        }

        public Criteria andTargetStatusIsNotNull() {
            addCriterion("target_status is not null");
            return (Criteria) this;
        }

        public Criteria andTargetStatusEqualTo(String value) {
            addCriterion("target_status =", value, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetStatusNotEqualTo(String value) {
            addCriterion("target_status <>", value, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetStatusGreaterThan(String value) {
            addCriterion("target_status >", value, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetStatusGreaterThanOrEqualTo(String value) {
            addCriterion("target_status >=", value, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetStatusLessThan(String value) {
            addCriterion("target_status <", value, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetStatusLessThanOrEqualTo(String value) {
            addCriterion("target_status <=", value, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetStatusLike(String value) {
            addCriterion("target_status like", value, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetStatusNotLike(String value) {
            addCriterion("target_status not like", value, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetStatusIn(List<String> values) {
            addCriterion("target_status in", values, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetStatusNotIn(List<String> values) {
            addCriterion("target_status not in", values, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetStatusBetween(String value1, String value2) {
            addCriterion("target_status between", value1, value2, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetStatusNotBetween(String value1, String value2) {
            addCriterion("target_status not between", value1, value2, "targetStatus");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadIsNull() {
            addCriterion("target_lines_read is null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadIsNotNull() {
            addCriterion("target_lines_read is not null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadEqualTo(String value) {
            addCriterion("target_lines_read =", value, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadNotEqualTo(String value) {
            addCriterion("target_lines_read <>", value, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadGreaterThan(String value) {
            addCriterion("target_lines_read >", value, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadGreaterThanOrEqualTo(String value) {
            addCriterion("target_lines_read >=", value, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadLessThan(String value) {
            addCriterion("target_lines_read <", value, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadLessThanOrEqualTo(String value) {
            addCriterion("target_lines_read <=", value, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadLike(String value) {
            addCriterion("target_lines_read like", value, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadNotLike(String value) {
            addCriterion("target_lines_read not like", value, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadIn(List<String> values) {
            addCriterion("target_lines_read in", values, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadNotIn(List<String> values) {
            addCriterion("target_lines_read not in", values, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadBetween(String value1, String value2) {
            addCriterion("target_lines_read between", value1, value2, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesReadNotBetween(String value1, String value2) {
            addCriterion("target_lines_read not between", value1, value2, "targetLinesRead");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenIsNull() {
            addCriterion("target_lines_written is null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenIsNotNull() {
            addCriterion("target_lines_written is not null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenEqualTo(String value) {
            addCriterion("target_lines_written =", value, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenNotEqualTo(String value) {
            addCriterion("target_lines_written <>", value, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenGreaterThan(String value) {
            addCriterion("target_lines_written >", value, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenGreaterThanOrEqualTo(String value) {
            addCriterion("target_lines_written >=", value, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenLessThan(String value) {
            addCriterion("target_lines_written <", value, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenLessThanOrEqualTo(String value) {
            addCriterion("target_lines_written <=", value, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenLike(String value) {
            addCriterion("target_lines_written like", value, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenNotLike(String value) {
            addCriterion("target_lines_written not like", value, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenIn(List<String> values) {
            addCriterion("target_lines_written in", values, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenNotIn(List<String> values) {
            addCriterion("target_lines_written not in", values, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenBetween(String value1, String value2) {
            addCriterion("target_lines_written between", value1, value2, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesWrittenNotBetween(String value1, String value2) {
            addCriterion("target_lines_written not between", value1, value2, "targetLinesWritten");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedIsNull() {
            addCriterion("target_lines_updated is null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedIsNotNull() {
            addCriterion("target_lines_updated is not null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedEqualTo(String value) {
            addCriterion("target_lines_updated =", value, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedNotEqualTo(String value) {
            addCriterion("target_lines_updated <>", value, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedGreaterThan(String value) {
            addCriterion("target_lines_updated >", value, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedGreaterThanOrEqualTo(String value) {
            addCriterion("target_lines_updated >=", value, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedLessThan(String value) {
            addCriterion("target_lines_updated <", value, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedLessThanOrEqualTo(String value) {
            addCriterion("target_lines_updated <=", value, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedLike(String value) {
            addCriterion("target_lines_updated like", value, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedNotLike(String value) {
            addCriterion("target_lines_updated not like", value, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedIn(List<String> values) {
            addCriterion("target_lines_updated in", values, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedNotIn(List<String> values) {
            addCriterion("target_lines_updated not in", values, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedBetween(String value1, String value2) {
            addCriterion("target_lines_updated between", value1, value2, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesUpdatedNotBetween(String value1, String value2) {
            addCriterion("target_lines_updated not between", value1, value2, "targetLinesUpdated");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputIsNull() {
            addCriterion("target_lines_input is null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputIsNotNull() {
            addCriterion("target_lines_input is not null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputEqualTo(String value) {
            addCriterion("target_lines_input =", value, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputNotEqualTo(String value) {
            addCriterion("target_lines_input <>", value, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputGreaterThan(String value) {
            addCriterion("target_lines_input >", value, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputGreaterThanOrEqualTo(String value) {
            addCriterion("target_lines_input >=", value, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputLessThan(String value) {
            addCriterion("target_lines_input <", value, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputLessThanOrEqualTo(String value) {
            addCriterion("target_lines_input <=", value, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputLike(String value) {
            addCriterion("target_lines_input like", value, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputNotLike(String value) {
            addCriterion("target_lines_input not like", value, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputIn(List<String> values) {
            addCriterion("target_lines_input in", values, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputNotIn(List<String> values) {
            addCriterion("target_lines_input not in", values, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputBetween(String value1, String value2) {
            addCriterion("target_lines_input between", value1, value2, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesInputNotBetween(String value1, String value2) {
            addCriterion("target_lines_input not between", value1, value2, "targetLinesInput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputIsNull() {
            addCriterion("target_lines_output is null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputIsNotNull() {
            addCriterion("target_lines_output is not null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputEqualTo(String value) {
            addCriterion("target_lines_output =", value, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputNotEqualTo(String value) {
            addCriterion("target_lines_output <>", value, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputGreaterThan(String value) {
            addCriterion("target_lines_output >", value, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputGreaterThanOrEqualTo(String value) {
            addCriterion("target_lines_output >=", value, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputLessThan(String value) {
            addCriterion("target_lines_output <", value, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputLessThanOrEqualTo(String value) {
            addCriterion("target_lines_output <=", value, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputLike(String value) {
            addCriterion("target_lines_output like", value, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputNotLike(String value) {
            addCriterion("target_lines_output not like", value, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputIn(List<String> values) {
            addCriterion("target_lines_output in", values, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputNotIn(List<String> values) {
            addCriterion("target_lines_output not in", values, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputBetween(String value1, String value2) {
            addCriterion("target_lines_output between", value1, value2, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesOutputNotBetween(String value1, String value2) {
            addCriterion("target_lines_output not between", value1, value2, "targetLinesOutput");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedIsNull() {
            addCriterion("target_lines_rejected is null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedIsNotNull() {
            addCriterion("target_lines_rejected is not null");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedEqualTo(String value) {
            addCriterion("target_lines_rejected =", value, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedNotEqualTo(String value) {
            addCriterion("target_lines_rejected <>", value, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedGreaterThan(String value) {
            addCriterion("target_lines_rejected >", value, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedGreaterThanOrEqualTo(String value) {
            addCriterion("target_lines_rejected >=", value, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedLessThan(String value) {
            addCriterion("target_lines_rejected <", value, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedLessThanOrEqualTo(String value) {
            addCriterion("target_lines_rejected <=", value, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedLike(String value) {
            addCriterion("target_lines_rejected like", value, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedNotLike(String value) {
            addCriterion("target_lines_rejected not like", value, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedIn(List<String> values) {
            addCriterion("target_lines_rejected in", values, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedNotIn(List<String> values) {
            addCriterion("target_lines_rejected not in", values, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedBetween(String value1, String value2) {
            addCriterion("target_lines_rejected between", value1, value2, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andTargetLinesRejectedNotBetween(String value1, String value2) {
            addCriterion("target_lines_rejected not between", value1, value2, "targetLinesRejected");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeIsNull() {
            addCriterion("monitor_type is null");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeIsNotNull() {
            addCriterion("monitor_type is not null");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeEqualTo(String value) {
            addCriterion("monitor_type =", value, "monitorType");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeNotEqualTo(String value) {
            addCriterion("monitor_type <>", value, "monitorType");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeGreaterThan(String value) {
            addCriterion("monitor_type >", value, "monitorType");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeGreaterThanOrEqualTo(String value) {
            addCriterion("monitor_type >=", value, "monitorType");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeLessThan(String value) {
            addCriterion("monitor_type <", value, "monitorType");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeLessThanOrEqualTo(String value) {
            addCriterion("monitor_type <=", value, "monitorType");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeLike(String value) {
            addCriterion("monitor_type like", value, "monitorType");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeNotLike(String value) {
            addCriterion("monitor_type not like", value, "monitorType");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeIn(List<String> values) {
            addCriterion("monitor_type in", values, "monitorType");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeNotIn(List<String> values) {
            addCriterion("monitor_type not in", values, "monitorType");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeBetween(String value1, String value2) {
            addCriterion("monitor_type between", value1, value2, "monitorType");
            return (Criteria) this;
        }

        public Criteria andMonitorTypeNotBetween(String value1, String value2) {
            addCriterion("monitor_type not between", value1, value2, "monitorType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_monitor
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 20 14:27:32 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}