package org.yaukie.frame.autocode.model;

import java.io.Serializable;
import java.util.Date;

public class XMonitor implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.id
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.monitor_id
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String monitorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.target_id
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.success_count
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String successCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.fail_count
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String failCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.target_status
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String targetStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.target_lines_read
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String targetLinesRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.target_lines_written
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String targetLinesWritten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.target_lines_updated
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String targetLinesUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.target_lines_input
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String targetLinesInput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.target_lines_output
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String targetLinesOutput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.target_lines_rejected
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String targetLinesRejected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.description
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.created_time
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.update_time
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_monitor.monitor_type
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private String monitorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.id
     *
     * @return the value of x_monitor.id
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.id
     *
     * @param id the value for x_monitor.id
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.monitor_id
     *
     * @return the value of x_monitor.monitor_id
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getMonitorId() {
        return monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.monitor_id
     *
     * @param monitorId the value for x_monitor.monitor_id
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setMonitorId(String monitorId) {
        this.monitorId = monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.target_id
     *
     * @return the value of x_monitor.target_id
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.target_id
     *
     * @param targetId the value for x_monitor.target_id
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.success_count
     *
     * @return the value of x_monitor.success_count
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getSuccessCount() {
        return successCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.success_count
     *
     * @param successCount the value for x_monitor.success_count
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setSuccessCount(String successCount) {
        this.successCount = successCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.fail_count
     *
     * @return the value of x_monitor.fail_count
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getFailCount() {
        return failCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.fail_count
     *
     * @param failCount the value for x_monitor.fail_count
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setFailCount(String failCount) {
        this.failCount = failCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.target_status
     *
     * @return the value of x_monitor.target_status
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getTargetStatus() {
        return targetStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.target_status
     *
     * @param targetStatus the value for x_monitor.target_status
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setTargetStatus(String targetStatus) {
        this.targetStatus = targetStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.target_lines_read
     *
     * @return the value of x_monitor.target_lines_read
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getTargetLinesRead() {
        return targetLinesRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.target_lines_read
     *
     * @param targetLinesRead the value for x_monitor.target_lines_read
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setTargetLinesRead(String targetLinesRead) {
        this.targetLinesRead = targetLinesRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.target_lines_written
     *
     * @return the value of x_monitor.target_lines_written
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getTargetLinesWritten() {
        return targetLinesWritten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.target_lines_written
     *
     * @param targetLinesWritten the value for x_monitor.target_lines_written
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setTargetLinesWritten(String targetLinesWritten) {
        this.targetLinesWritten = targetLinesWritten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.target_lines_updated
     *
     * @return the value of x_monitor.target_lines_updated
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getTargetLinesUpdated() {
        return targetLinesUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.target_lines_updated
     *
     * @param targetLinesUpdated the value for x_monitor.target_lines_updated
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setTargetLinesUpdated(String targetLinesUpdated) {
        this.targetLinesUpdated = targetLinesUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.target_lines_input
     *
     * @return the value of x_monitor.target_lines_input
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getTargetLinesInput() {
        return targetLinesInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.target_lines_input
     *
     * @param targetLinesInput the value for x_monitor.target_lines_input
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setTargetLinesInput(String targetLinesInput) {
        this.targetLinesInput = targetLinesInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.target_lines_output
     *
     * @return the value of x_monitor.target_lines_output
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getTargetLinesOutput() {
        return targetLinesOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.target_lines_output
     *
     * @param targetLinesOutput the value for x_monitor.target_lines_output
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setTargetLinesOutput(String targetLinesOutput) {
        this.targetLinesOutput = targetLinesOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.target_lines_rejected
     *
     * @return the value of x_monitor.target_lines_rejected
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getTargetLinesRejected() {
        return targetLinesRejected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.target_lines_rejected
     *
     * @param targetLinesRejected the value for x_monitor.target_lines_rejected
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setTargetLinesRejected(String targetLinesRejected) {
        this.targetLinesRejected = targetLinesRejected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.description
     *
     * @return the value of x_monitor.description
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.description
     *
     * @param description the value for x_monitor.description
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.created_time
     *
     * @return the value of x_monitor.created_time
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.created_time
     *
     * @param createdTime the value for x_monitor.created_time
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.update_time
     *
     * @return the value of x_monitor.update_time
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.update_time
     *
     * @param updateTime the value for x_monitor.update_time
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_monitor.monitor_type
     *
     * @return the value of x_monitor.monitor_type
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public String getMonitorType() {
        return monitorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_monitor.monitor_type
     *
     * @param monitorType the value for x_monitor.monitor_type
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    public void setMonitorType(String monitorType) {
        this.monitorType = monitorType;
    }
}