package org.yaukie.frame.autocode.model;

import java.io.Serializable;
import java.util.Date;

public class XParams implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_params.id
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_params.obj_code
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    private String objCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_params.obj_val
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    private String objVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_params.obj_name
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    private String objName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_params.obj_des
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    private String objDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_params.target_id
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    private String targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_params.target_type
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    private String targetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_params.is_use
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    private String isUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_params.created_time
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_params.update_time
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_params.id
     *
     * @return the value of x_params.id
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_params.id
     *
     * @param id the value for x_params.id
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_params.obj_code
     *
     * @return the value of x_params.obj_code
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public String getObjCode() {
        return objCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_params.obj_code
     *
     * @param objCode the value for x_params.obj_code
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public void setObjCode(String objCode) {
        this.objCode = objCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_params.obj_val
     *
     * @return the value of x_params.obj_val
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public String getObjVal() {
        return objVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_params.obj_val
     *
     * @param objVal the value for x_params.obj_val
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public void setObjVal(String objVal) {
        this.objVal = objVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_params.obj_name
     *
     * @return the value of x_params.obj_name
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public String getObjName() {
        return objName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_params.obj_name
     *
     * @param objName the value for x_params.obj_name
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public void setObjName(String objName) {
        this.objName = objName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_params.obj_des
     *
     * @return the value of x_params.obj_des
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public String getObjDes() {
        return objDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_params.obj_des
     *
     * @param objDes the value for x_params.obj_des
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public void setObjDes(String objDes) {
        this.objDes = objDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_params.target_id
     *
     * @return the value of x_params.target_id
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_params.target_id
     *
     * @param targetId the value for x_params.target_id
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_params.target_type
     *
     * @return the value of x_params.target_type
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_params.target_type
     *
     * @param targetType the value for x_params.target_type
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_params.is_use
     *
     * @return the value of x_params.is_use
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public String getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_params.is_use
     *
     * @param isUse the value for x_params.is_use
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public void setIsUse(String isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_params.created_time
     *
     * @return the value of x_params.created_time
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_params.created_time
     *
     * @param createdTime the value for x_params.created_time
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_params.update_time
     *
     * @return the value of x_params.update_time
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_params.update_time
     *
     * @param updateTime the value for x_params.update_time
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}