package org.yaukie.frame.autocode.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XQuartzExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    public XQuartzExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andQuartzIdIsNull() {
            addCriterion("quartz_id is null");
            return (Criteria) this;
        }

        public Criteria andQuartzIdIsNotNull() {
            addCriterion("quartz_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuartzIdEqualTo(String value) {
            addCriterion("quartz_id =", value, "quartzId");
            return (Criteria) this;
        }

        public Criteria andQuartzIdNotEqualTo(String value) {
            addCriterion("quartz_id <>", value, "quartzId");
            return (Criteria) this;
        }

        public Criteria andQuartzIdGreaterThan(String value) {
            addCriterion("quartz_id >", value, "quartzId");
            return (Criteria) this;
        }

        public Criteria andQuartzIdGreaterThanOrEqualTo(String value) {
            addCriterion("quartz_id >=", value, "quartzId");
            return (Criteria) this;
        }

        public Criteria andQuartzIdLessThan(String value) {
            addCriterion("quartz_id <", value, "quartzId");
            return (Criteria) this;
        }

        public Criteria andQuartzIdLessThanOrEqualTo(String value) {
            addCriterion("quartz_id <=", value, "quartzId");
            return (Criteria) this;
        }

        public Criteria andQuartzIdLike(String value) {
            addCriterion("quartz_id like", value, "quartzId");
            return (Criteria) this;
        }

        public Criteria andQuartzIdNotLike(String value) {
            addCriterion("quartz_id not like", value, "quartzId");
            return (Criteria) this;
        }

        public Criteria andQuartzIdIn(List<String> values) {
            addCriterion("quartz_id in", values, "quartzId");
            return (Criteria) this;
        }

        public Criteria andQuartzIdNotIn(List<String> values) {
            addCriterion("quartz_id not in", values, "quartzId");
            return (Criteria) this;
        }

        public Criteria andQuartzIdBetween(String value1, String value2) {
            addCriterion("quartz_id between", value1, value2, "quartzId");
            return (Criteria) this;
        }

        public Criteria andQuartzIdNotBetween(String value1, String value2) {
            addCriterion("quartz_id not between", value1, value2, "quartzId");
            return (Criteria) this;
        }

        public Criteria andTargetIdIsNull() {
            addCriterion("target_id is null");
            return (Criteria) this;
        }

        public Criteria andTargetIdIsNotNull() {
            addCriterion("target_id is not null");
            return (Criteria) this;
        }

        public Criteria andTargetIdEqualTo(String value) {
            addCriterion("target_id =", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotEqualTo(String value) {
            addCriterion("target_id <>", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThan(String value) {
            addCriterion("target_id >", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThanOrEqualTo(String value) {
            addCriterion("target_id >=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThan(String value) {
            addCriterion("target_id <", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThanOrEqualTo(String value) {
            addCriterion("target_id <=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLike(String value) {
            addCriterion("target_id like", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotLike(String value) {
            addCriterion("target_id not like", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdIn(List<String> values) {
            addCriterion("target_id in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotIn(List<String> values) {
            addCriterion("target_id not in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdBetween(String value1, String value2) {
            addCriterion("target_id between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotBetween(String value1, String value2) {
            addCriterion("target_id not between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeIsNull() {
            addCriterion("quartz_type is null");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeIsNotNull() {
            addCriterion("quartz_type is not null");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeEqualTo(String value) {
            addCriterion("quartz_type =", value, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeNotEqualTo(String value) {
            addCriterion("quartz_type <>", value, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeGreaterThan(String value) {
            addCriterion("quartz_type >", value, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeGreaterThanOrEqualTo(String value) {
            addCriterion("quartz_type >=", value, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeLessThan(String value) {
            addCriterion("quartz_type <", value, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeLessThanOrEqualTo(String value) {
            addCriterion("quartz_type <=", value, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeLike(String value) {
            addCriterion("quartz_type like", value, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeNotLike(String value) {
            addCriterion("quartz_type not like", value, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeIn(List<String> values) {
            addCriterion("quartz_type in", values, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeNotIn(List<String> values) {
            addCriterion("quartz_type not in", values, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeBetween(String value1, String value2) {
            addCriterion("quartz_type between", value1, value2, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzTypeNotBetween(String value1, String value2) {
            addCriterion("quartz_type not between", value1, value2, "quartzType");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionIsNull() {
            addCriterion("quartz_description is null");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionIsNotNull() {
            addCriterion("quartz_description is not null");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionEqualTo(String value) {
            addCriterion("quartz_description =", value, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionNotEqualTo(String value) {
            addCriterion("quartz_description <>", value, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionGreaterThan(String value) {
            addCriterion("quartz_description >", value, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("quartz_description >=", value, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionLessThan(String value) {
            addCriterion("quartz_description <", value, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionLessThanOrEqualTo(String value) {
            addCriterion("quartz_description <=", value, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionLike(String value) {
            addCriterion("quartz_description like", value, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionNotLike(String value) {
            addCriterion("quartz_description not like", value, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionIn(List<String> values) {
            addCriterion("quartz_description in", values, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionNotIn(List<String> values) {
            addCriterion("quartz_description not in", values, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionBetween(String value1, String value2) {
            addCriterion("quartz_description between", value1, value2, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzDescriptionNotBetween(String value1, String value2) {
            addCriterion("quartz_description not between", value1, value2, "quartzDescription");
            return (Criteria) this;
        }

        public Criteria andQuartzCronIsNull() {
            addCriterion("quartz_cron is null");
            return (Criteria) this;
        }

        public Criteria andQuartzCronIsNotNull() {
            addCriterion("quartz_cron is not null");
            return (Criteria) this;
        }

        public Criteria andQuartzCronEqualTo(String value) {
            addCriterion("quartz_cron =", value, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andQuartzCronNotEqualTo(String value) {
            addCriterion("quartz_cron <>", value, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andQuartzCronGreaterThan(String value) {
            addCriterion("quartz_cron >", value, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andQuartzCronGreaterThanOrEqualTo(String value) {
            addCriterion("quartz_cron >=", value, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andQuartzCronLessThan(String value) {
            addCriterion("quartz_cron <", value, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andQuartzCronLessThanOrEqualTo(String value) {
            addCriterion("quartz_cron <=", value, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andQuartzCronLike(String value) {
            addCriterion("quartz_cron like", value, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andQuartzCronNotLike(String value) {
            addCriterion("quartz_cron not like", value, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andQuartzCronIn(List<String> values) {
            addCriterion("quartz_cron in", values, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andQuartzCronNotIn(List<String> values) {
            addCriterion("quartz_cron not in", values, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andQuartzCronBetween(String value1, String value2) {
            addCriterion("quartz_cron between", value1, value2, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andQuartzCronNotBetween(String value1, String value2) {
            addCriterion("quartz_cron not between", value1, value2, "quartzCron");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(String value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(String value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(String value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(String value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(String value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(String value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLike(String value) {
            addCriterion("is_del like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotLike(String value) {
            addCriterion("is_del not like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<String> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<String> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(String value1, String value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(String value1, String value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_quartz
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 13 15:46:31 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_quartz
     *
     * @mbg.generated Fri Nov 13 15:46:31 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}