package org.yaukie.frame.autocode.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XRepositoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    public XRepositoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRepoIdIsNull() {
            addCriterion("repo_id is null");
            return (Criteria) this;
        }

        public Criteria andRepoIdIsNotNull() {
            addCriterion("repo_id is not null");
            return (Criteria) this;
        }

        public Criteria andRepoIdEqualTo(String value) {
            addCriterion("repo_id =", value, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoIdNotEqualTo(String value) {
            addCriterion("repo_id <>", value, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoIdGreaterThan(String value) {
            addCriterion("repo_id >", value, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoIdGreaterThanOrEqualTo(String value) {
            addCriterion("repo_id >=", value, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoIdLessThan(String value) {
            addCriterion("repo_id <", value, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoIdLessThanOrEqualTo(String value) {
            addCriterion("repo_id <=", value, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoIdLike(String value) {
            addCriterion("repo_id like", value, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoIdNotLike(String value) {
            addCriterion("repo_id not like", value, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoIdIn(List<String> values) {
            addCriterion("repo_id in", values, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoIdNotIn(List<String> values) {
            addCriterion("repo_id not in", values, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoIdBetween(String value1, String value2) {
            addCriterion("repo_id between", value1, value2, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoIdNotBetween(String value1, String value2) {
            addCriterion("repo_id not between", value1, value2, "repoId");
            return (Criteria) this;
        }

        public Criteria andRepoNameIsNull() {
            addCriterion("repo_name is null");
            return (Criteria) this;
        }

        public Criteria andRepoNameIsNotNull() {
            addCriterion("repo_name is not null");
            return (Criteria) this;
        }

        public Criteria andRepoNameEqualTo(String value) {
            addCriterion("repo_name =", value, "repoName");
            return (Criteria) this;
        }

        public Criteria andRepoNameNotEqualTo(String value) {
            addCriterion("repo_name <>", value, "repoName");
            return (Criteria) this;
        }

        public Criteria andRepoNameGreaterThan(String value) {
            addCriterion("repo_name >", value, "repoName");
            return (Criteria) this;
        }

        public Criteria andRepoNameGreaterThanOrEqualTo(String value) {
            addCriterion("repo_name >=", value, "repoName");
            return (Criteria) this;
        }

        public Criteria andRepoNameLessThan(String value) {
            addCriterion("repo_name <", value, "repoName");
            return (Criteria) this;
        }

        public Criteria andRepoNameLessThanOrEqualTo(String value) {
            addCriterion("repo_name <=", value, "repoName");
            return (Criteria) this;
        }

        public Criteria andRepoNameLike(String value) {
            addCriterion("repo_name like", value, "repoName");
            return (Criteria) this;
        }

        public Criteria andRepoNameNotLike(String value) {
            addCriterion("repo_name not like", value, "repoName");
            return (Criteria) this;
        }

        public Criteria andRepoNameIn(List<String> values) {
            addCriterion("repo_name in", values, "repoName");
            return (Criteria) this;
        }

        public Criteria andRepoNameNotIn(List<String> values) {
            addCriterion("repo_name not in", values, "repoName");
            return (Criteria) this;
        }

        public Criteria andRepoNameBetween(String value1, String value2) {
            addCriterion("repo_name between", value1, value2, "repoName");
            return (Criteria) this;
        }

        public Criteria andRepoNameNotBetween(String value1, String value2) {
            addCriterion("repo_name not between", value1, value2, "repoName");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBaseDirIsNull() {
            addCriterion("base_dir is null");
            return (Criteria) this;
        }

        public Criteria andBaseDirIsNotNull() {
            addCriterion("base_dir is not null");
            return (Criteria) this;
        }

        public Criteria andBaseDirEqualTo(String value) {
            addCriterion("base_dir =", value, "baseDir");
            return (Criteria) this;
        }

        public Criteria andBaseDirNotEqualTo(String value) {
            addCriterion("base_dir <>", value, "baseDir");
            return (Criteria) this;
        }

        public Criteria andBaseDirGreaterThan(String value) {
            addCriterion("base_dir >", value, "baseDir");
            return (Criteria) this;
        }

        public Criteria andBaseDirGreaterThanOrEqualTo(String value) {
            addCriterion("base_dir >=", value, "baseDir");
            return (Criteria) this;
        }

        public Criteria andBaseDirLessThan(String value) {
            addCriterion("base_dir <", value, "baseDir");
            return (Criteria) this;
        }

        public Criteria andBaseDirLessThanOrEqualTo(String value) {
            addCriterion("base_dir <=", value, "baseDir");
            return (Criteria) this;
        }

        public Criteria andBaseDirLike(String value) {
            addCriterion("base_dir like", value, "baseDir");
            return (Criteria) this;
        }

        public Criteria andBaseDirNotLike(String value) {
            addCriterion("base_dir not like", value, "baseDir");
            return (Criteria) this;
        }

        public Criteria andBaseDirIn(List<String> values) {
            addCriterion("base_dir in", values, "baseDir");
            return (Criteria) this;
        }

        public Criteria andBaseDirNotIn(List<String> values) {
            addCriterion("base_dir not in", values, "baseDir");
            return (Criteria) this;
        }

        public Criteria andBaseDirBetween(String value1, String value2) {
            addCriterion("base_dir between", value1, value2, "baseDir");
            return (Criteria) this;
        }

        public Criteria andBaseDirNotBetween(String value1, String value2) {
            addCriterion("base_dir not between", value1, value2, "baseDir");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameIsNull() {
            addCriterion("repo_username is null");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameIsNotNull() {
            addCriterion("repo_username is not null");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameEqualTo(String value) {
            addCriterion("repo_username =", value, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameNotEqualTo(String value) {
            addCriterion("repo_username <>", value, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameGreaterThan(String value) {
            addCriterion("repo_username >", value, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("repo_username >=", value, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameLessThan(String value) {
            addCriterion("repo_username <", value, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameLessThanOrEqualTo(String value) {
            addCriterion("repo_username <=", value, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameLike(String value) {
            addCriterion("repo_username like", value, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameNotLike(String value) {
            addCriterion("repo_username not like", value, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameIn(List<String> values) {
            addCriterion("repo_username in", values, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameNotIn(List<String> values) {
            addCriterion("repo_username not in", values, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameBetween(String value1, String value2) {
            addCriterion("repo_username between", value1, value2, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoUsernameNotBetween(String value1, String value2) {
            addCriterion("repo_username not between", value1, value2, "repoUsername");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordIsNull() {
            addCriterion("repo_password is null");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordIsNotNull() {
            addCriterion("repo_password is not null");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordEqualTo(String value) {
            addCriterion("repo_password =", value, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordNotEqualTo(String value) {
            addCriterion("repo_password <>", value, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordGreaterThan(String value) {
            addCriterion("repo_password >", value, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("repo_password >=", value, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordLessThan(String value) {
            addCriterion("repo_password <", value, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordLessThanOrEqualTo(String value) {
            addCriterion("repo_password <=", value, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordLike(String value) {
            addCriterion("repo_password like", value, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordNotLike(String value) {
            addCriterion("repo_password not like", value, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordIn(List<String> values) {
            addCriterion("repo_password in", values, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordNotIn(List<String> values) {
            addCriterion("repo_password not in", values, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordBetween(String value1, String value2) {
            addCriterion("repo_password between", value1, value2, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoPasswordNotBetween(String value1, String value2) {
            addCriterion("repo_password not between", value1, value2, "repoPassword");
            return (Criteria) this;
        }

        public Criteria andRepoTypeIsNull() {
            addCriterion("repo_type is null");
            return (Criteria) this;
        }

        public Criteria andRepoTypeIsNotNull() {
            addCriterion("repo_type is not null");
            return (Criteria) this;
        }

        public Criteria andRepoTypeEqualTo(String value) {
            addCriterion("repo_type =", value, "repoType");
            return (Criteria) this;
        }

        public Criteria andRepoTypeNotEqualTo(String value) {
            addCriterion("repo_type <>", value, "repoType");
            return (Criteria) this;
        }

        public Criteria andRepoTypeGreaterThan(String value) {
            addCriterion("repo_type >", value, "repoType");
            return (Criteria) this;
        }

        public Criteria andRepoTypeGreaterThanOrEqualTo(String value) {
            addCriterion("repo_type >=", value, "repoType");
            return (Criteria) this;
        }

        public Criteria andRepoTypeLessThan(String value) {
            addCriterion("repo_type <", value, "repoType");
            return (Criteria) this;
        }

        public Criteria andRepoTypeLessThanOrEqualTo(String value) {
            addCriterion("repo_type <=", value, "repoType");
            return (Criteria) this;
        }

        public Criteria andRepoTypeLike(String value) {
            addCriterion("repo_type like", value, "repoType");
            return (Criteria) this;
        }

        public Criteria andRepoTypeNotLike(String value) {
            addCriterion("repo_type not like", value, "repoType");
            return (Criteria) this;
        }

        public Criteria andRepoTypeIn(List<String> values) {
            addCriterion("repo_type in", values, "repoType");
            return (Criteria) this;
        }

        public Criteria andRepoTypeNotIn(List<String> values) {
            addCriterion("repo_type not in", values, "repoType");
            return (Criteria) this;
        }

        public Criteria andRepoTypeBetween(String value1, String value2) {
            addCriterion("repo_type between", value1, value2, "repoType");
            return (Criteria) this;
        }

        public Criteria andRepoTypeNotBetween(String value1, String value2) {
            addCriterion("repo_type not between", value1, value2, "repoType");
            return (Criteria) this;
        }

        public Criteria andDbAccessIsNull() {
            addCriterion("db_access is null");
            return (Criteria) this;
        }

        public Criteria andDbAccessIsNotNull() {
            addCriterion("db_access is not null");
            return (Criteria) this;
        }

        public Criteria andDbAccessEqualTo(String value) {
            addCriterion("db_access =", value, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbAccessNotEqualTo(String value) {
            addCriterion("db_access <>", value, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbAccessGreaterThan(String value) {
            addCriterion("db_access >", value, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbAccessGreaterThanOrEqualTo(String value) {
            addCriterion("db_access >=", value, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbAccessLessThan(String value) {
            addCriterion("db_access <", value, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbAccessLessThanOrEqualTo(String value) {
            addCriterion("db_access <=", value, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbAccessLike(String value) {
            addCriterion("db_access like", value, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbAccessNotLike(String value) {
            addCriterion("db_access not like", value, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbAccessIn(List<String> values) {
            addCriterion("db_access in", values, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbAccessNotIn(List<String> values) {
            addCriterion("db_access not in", values, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbAccessBetween(String value1, String value2) {
            addCriterion("db_access between", value1, value2, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbAccessNotBetween(String value1, String value2) {
            addCriterion("db_access not between", value1, value2, "dbAccess");
            return (Criteria) this;
        }

        public Criteria andDbHostIsNull() {
            addCriterion("db_host is null");
            return (Criteria) this;
        }

        public Criteria andDbHostIsNotNull() {
            addCriterion("db_host is not null");
            return (Criteria) this;
        }

        public Criteria andDbHostEqualTo(String value) {
            addCriterion("db_host =", value, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbHostNotEqualTo(String value) {
            addCriterion("db_host <>", value, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbHostGreaterThan(String value) {
            addCriterion("db_host >", value, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbHostGreaterThanOrEqualTo(String value) {
            addCriterion("db_host >=", value, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbHostLessThan(String value) {
            addCriterion("db_host <", value, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbHostLessThanOrEqualTo(String value) {
            addCriterion("db_host <=", value, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbHostLike(String value) {
            addCriterion("db_host like", value, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbHostNotLike(String value) {
            addCriterion("db_host not like", value, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbHostIn(List<String> values) {
            addCriterion("db_host in", values, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbHostNotIn(List<String> values) {
            addCriterion("db_host not in", values, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbHostBetween(String value1, String value2) {
            addCriterion("db_host between", value1, value2, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbHostNotBetween(String value1, String value2) {
            addCriterion("db_host not between", value1, value2, "dbHost");
            return (Criteria) this;
        }

        public Criteria andDbPortIsNull() {
            addCriterion("db_port is null");
            return (Criteria) this;
        }

        public Criteria andDbPortIsNotNull() {
            addCriterion("db_port is not null");
            return (Criteria) this;
        }

        public Criteria andDbPortEqualTo(String value) {
            addCriterion("db_port =", value, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbPortNotEqualTo(String value) {
            addCriterion("db_port <>", value, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbPortGreaterThan(String value) {
            addCriterion("db_port >", value, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbPortGreaterThanOrEqualTo(String value) {
            addCriterion("db_port >=", value, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbPortLessThan(String value) {
            addCriterion("db_port <", value, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbPortLessThanOrEqualTo(String value) {
            addCriterion("db_port <=", value, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbPortLike(String value) {
            addCriterion("db_port like", value, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbPortNotLike(String value) {
            addCriterion("db_port not like", value, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbPortIn(List<String> values) {
            addCriterion("db_port in", values, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbPortNotIn(List<String> values) {
            addCriterion("db_port not in", values, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbPortBetween(String value1, String value2) {
            addCriterion("db_port between", value1, value2, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbPortNotBetween(String value1, String value2) {
            addCriterion("db_port not between", value1, value2, "dbPort");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNull() {
            addCriterion("db_name is null");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNotNull() {
            addCriterion("db_name is not null");
            return (Criteria) this;
        }

        public Criteria andDbNameEqualTo(String value) {
            addCriterion("db_name =", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotEqualTo(String value) {
            addCriterion("db_name <>", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThan(String value) {
            addCriterion("db_name >", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThanOrEqualTo(String value) {
            addCriterion("db_name >=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThan(String value) {
            addCriterion("db_name <", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThanOrEqualTo(String value) {
            addCriterion("db_name <=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLike(String value) {
            addCriterion("db_name like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotLike(String value) {
            addCriterion("db_name not like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameIn(List<String> values) {
            addCriterion("db_name in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotIn(List<String> values) {
            addCriterion("db_name not in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameBetween(String value1, String value2) {
            addCriterion("db_name between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotBetween(String value1, String value2) {
            addCriterion("db_name not between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbUsernameIsNull() {
            addCriterion("db_username is null");
            return (Criteria) this;
        }

        public Criteria andDbUsernameIsNotNull() {
            addCriterion("db_username is not null");
            return (Criteria) this;
        }

        public Criteria andDbUsernameEqualTo(String value) {
            addCriterion("db_username =", value, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbUsernameNotEqualTo(String value) {
            addCriterion("db_username <>", value, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbUsernameGreaterThan(String value) {
            addCriterion("db_username >", value, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("db_username >=", value, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbUsernameLessThan(String value) {
            addCriterion("db_username <", value, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbUsernameLessThanOrEqualTo(String value) {
            addCriterion("db_username <=", value, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbUsernameLike(String value) {
            addCriterion("db_username like", value, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbUsernameNotLike(String value) {
            addCriterion("db_username not like", value, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbUsernameIn(List<String> values) {
            addCriterion("db_username in", values, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbUsernameNotIn(List<String> values) {
            addCriterion("db_username not in", values, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbUsernameBetween(String value1, String value2) {
            addCriterion("db_username between", value1, value2, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbUsernameNotBetween(String value1, String value2) {
            addCriterion("db_username not between", value1, value2, "dbUsername");
            return (Criteria) this;
        }

        public Criteria andDbPasswordIsNull() {
            addCriterion("db_password is null");
            return (Criteria) this;
        }

        public Criteria andDbPasswordIsNotNull() {
            addCriterion("db_password is not null");
            return (Criteria) this;
        }

        public Criteria andDbPasswordEqualTo(String value) {
            addCriterion("db_password =", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordNotEqualTo(String value) {
            addCriterion("db_password <>", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordGreaterThan(String value) {
            addCriterion("db_password >", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("db_password >=", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordLessThan(String value) {
            addCriterion("db_password <", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordLessThanOrEqualTo(String value) {
            addCriterion("db_password <=", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordLike(String value) {
            addCriterion("db_password like", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordNotLike(String value) {
            addCriterion("db_password not like", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordIn(List<String> values) {
            addCriterion("db_password in", values, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordNotIn(List<String> values) {
            addCriterion("db_password not in", values, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordBetween(String value1, String value2) {
            addCriterion("db_password between", value1, value2, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordNotBetween(String value1, String value2) {
            addCriterion("db_password not between", value1, value2, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(String value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(String value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(String value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(String value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(String value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(String value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLike(String value) {
            addCriterion("is_del like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotLike(String value) {
            addCriterion("is_del not like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<String> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<String> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(String value1, String value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(String value1, String value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_repository
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 23 19:21:47 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_repository
     *
     * @mbg.generated Mon Nov 23 19:21:47 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}