package org.yaukie.frame.autocode.model;

import java.io.Serializable;
import java.util.Date;

public class XTemplate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_template.id
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_template.template_key
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    private String templateKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_template.template_name
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_template.template_path
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    private String templatePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_template.template_description
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    private String templateDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_template.created_time
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_template.update_time
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_template.id
     *
     * @return the value of x_template.id
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_template.id
     *
     * @param id the value for x_template.id
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_template.template_key
     *
     * @return the value of x_template.template_key
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public String getTemplateKey() {
        return templateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_template.template_key
     *
     * @param templateKey the value for x_template.template_key
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public void setTemplateKey(String templateKey) {
        this.templateKey = templateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_template.template_name
     *
     * @return the value of x_template.template_name
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_template.template_name
     *
     * @param templateName the value for x_template.template_name
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_template.template_path
     *
     * @return the value of x_template.template_path
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public String getTemplatePath() {
        return templatePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_template.template_path
     *
     * @param templatePath the value for x_template.template_path
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public void setTemplatePath(String templatePath) {
        this.templatePath = templatePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_template.template_description
     *
     * @return the value of x_template.template_description
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public String getTemplateDescription() {
        return templateDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_template.template_description
     *
     * @param templateDescription the value for x_template.template_description
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public void setTemplateDescription(String templateDescription) {
        this.templateDescription = templateDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_template.created_time
     *
     * @return the value of x_template.created_time
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_template.created_time
     *
     * @param createdTime the value for x_template.created_time
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_template.update_time
     *
     * @return the value of x_template.update_time
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_template.update_time
     *
     * @param updateTime the value for x_template.update_time
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}