package org.yaukie.frame.autocode.model;

import java.io.Serializable;
import java.util.Date;

public class XTrans implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.id
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.trans_id
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private String transId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.trans_name
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private String transName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.trans_description
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private String transDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.trans_type
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private String transType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.trans_path
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private String transPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.trans_repository_id
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private String transRepositoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.trans_log_level
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private String transLogLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.trans_status
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private String transStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.is_del
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private String isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.created_time
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.update_time
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.is_monitor_enabled
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private String isMonitorEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_trans.tpl_key
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private String tplKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.id
     *
     * @return the value of x_trans.id
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.id
     *
     * @param id the value for x_trans.id
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.trans_id
     *
     * @return the value of x_trans.trans_id
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.trans_id
     *
     * @param transId the value for x_trans.trans_id
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setTransId(String transId) {
        this.transId = transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.trans_name
     *
     * @return the value of x_trans.trans_name
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getTransName() {
        return transName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.trans_name
     *
     * @param transName the value for x_trans.trans_name
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setTransName(String transName) {
        this.transName = transName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.trans_description
     *
     * @return the value of x_trans.trans_description
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getTransDescription() {
        return transDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.trans_description
     *
     * @param transDescription the value for x_trans.trans_description
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setTransDescription(String transDescription) {
        this.transDescription = transDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.trans_type
     *
     * @return the value of x_trans.trans_type
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getTransType() {
        return transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.trans_type
     *
     * @param transType the value for x_trans.trans_type
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setTransType(String transType) {
        this.transType = transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.trans_path
     *
     * @return the value of x_trans.trans_path
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getTransPath() {
        return transPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.trans_path
     *
     * @param transPath the value for x_trans.trans_path
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setTransPath(String transPath) {
        this.transPath = transPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.trans_repository_id
     *
     * @return the value of x_trans.trans_repository_id
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getTransRepositoryId() {
        return transRepositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.trans_repository_id
     *
     * @param transRepositoryId the value for x_trans.trans_repository_id
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setTransRepositoryId(String transRepositoryId) {
        this.transRepositoryId = transRepositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.trans_log_level
     *
     * @return the value of x_trans.trans_log_level
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getTransLogLevel() {
        return transLogLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.trans_log_level
     *
     * @param transLogLevel the value for x_trans.trans_log_level
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setTransLogLevel(String transLogLevel) {
        this.transLogLevel = transLogLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.trans_status
     *
     * @return the value of x_trans.trans_status
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getTransStatus() {
        return transStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.trans_status
     *
     * @param transStatus the value for x_trans.trans_status
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setTransStatus(String transStatus) {
        this.transStatus = transStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.is_del
     *
     * @return the value of x_trans.is_del
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.is_del
     *
     * @param isDel the value for x_trans.is_del
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.created_time
     *
     * @return the value of x_trans.created_time
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.created_time
     *
     * @param createdTime the value for x_trans.created_time
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.update_time
     *
     * @return the value of x_trans.update_time
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.update_time
     *
     * @param updateTime the value for x_trans.update_time
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.is_monitor_enabled
     *
     * @return the value of x_trans.is_monitor_enabled
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getIsMonitorEnabled() {
        return isMonitorEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.is_monitor_enabled
     *
     * @param isMonitorEnabled the value for x_trans.is_monitor_enabled
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setIsMonitorEnabled(String isMonitorEnabled) {
        this.isMonitorEnabled = isMonitorEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_trans.tpl_key
     *
     * @return the value of x_trans.tpl_key
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getTplKey() {
        return tplKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_trans.tpl_key
     *
     * @param tplKey the value for x_trans.tpl_key
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setTplKey(String tplKey) {
        this.tplKey = tplKey;
    }
}