package org.yaukie.frame.autocode.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XTransExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public XTransExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTransIdIsNull() {
            addCriterion("trans_id is null");
            return (Criteria) this;
        }

        public Criteria andTransIdIsNotNull() {
            addCriterion("trans_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransIdEqualTo(String value) {
            addCriterion("trans_id =", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdNotEqualTo(String value) {
            addCriterion("trans_id <>", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdGreaterThan(String value) {
            addCriterion("trans_id >", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdGreaterThanOrEqualTo(String value) {
            addCriterion("trans_id >=", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdLessThan(String value) {
            addCriterion("trans_id <", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdLessThanOrEqualTo(String value) {
            addCriterion("trans_id <=", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdLike(String value) {
            addCriterion("trans_id like", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdNotLike(String value) {
            addCriterion("trans_id not like", value, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdIn(List<String> values) {
            addCriterion("trans_id in", values, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdNotIn(List<String> values) {
            addCriterion("trans_id not in", values, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdBetween(String value1, String value2) {
            addCriterion("trans_id between", value1, value2, "transId");
            return (Criteria) this;
        }

        public Criteria andTransIdNotBetween(String value1, String value2) {
            addCriterion("trans_id not between", value1, value2, "transId");
            return (Criteria) this;
        }

        public Criteria andTransNameIsNull() {
            addCriterion("trans_name is null");
            return (Criteria) this;
        }

        public Criteria andTransNameIsNotNull() {
            addCriterion("trans_name is not null");
            return (Criteria) this;
        }

        public Criteria andTransNameEqualTo(String value) {
            addCriterion("trans_name =", value, "transName");
            return (Criteria) this;
        }

        public Criteria andTransNameNotEqualTo(String value) {
            addCriterion("trans_name <>", value, "transName");
            return (Criteria) this;
        }

        public Criteria andTransNameGreaterThan(String value) {
            addCriterion("trans_name >", value, "transName");
            return (Criteria) this;
        }

        public Criteria andTransNameGreaterThanOrEqualTo(String value) {
            addCriterion("trans_name >=", value, "transName");
            return (Criteria) this;
        }

        public Criteria andTransNameLessThan(String value) {
            addCriterion("trans_name <", value, "transName");
            return (Criteria) this;
        }

        public Criteria andTransNameLessThanOrEqualTo(String value) {
            addCriterion("trans_name <=", value, "transName");
            return (Criteria) this;
        }

        public Criteria andTransNameLike(String value) {
            addCriterion("trans_name like", value, "transName");
            return (Criteria) this;
        }

        public Criteria andTransNameNotLike(String value) {
            addCriterion("trans_name not like", value, "transName");
            return (Criteria) this;
        }

        public Criteria andTransNameIn(List<String> values) {
            addCriterion("trans_name in", values, "transName");
            return (Criteria) this;
        }

        public Criteria andTransNameNotIn(List<String> values) {
            addCriterion("trans_name not in", values, "transName");
            return (Criteria) this;
        }

        public Criteria andTransNameBetween(String value1, String value2) {
            addCriterion("trans_name between", value1, value2, "transName");
            return (Criteria) this;
        }

        public Criteria andTransNameNotBetween(String value1, String value2) {
            addCriterion("trans_name not between", value1, value2, "transName");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionIsNull() {
            addCriterion("trans_description is null");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionIsNotNull() {
            addCriterion("trans_description is not null");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionEqualTo(String value) {
            addCriterion("trans_description =", value, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionNotEqualTo(String value) {
            addCriterion("trans_description <>", value, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionGreaterThan(String value) {
            addCriterion("trans_description >", value, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("trans_description >=", value, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionLessThan(String value) {
            addCriterion("trans_description <", value, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionLessThanOrEqualTo(String value) {
            addCriterion("trans_description <=", value, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionLike(String value) {
            addCriterion("trans_description like", value, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionNotLike(String value) {
            addCriterion("trans_description not like", value, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionIn(List<String> values) {
            addCriterion("trans_description in", values, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionNotIn(List<String> values) {
            addCriterion("trans_description not in", values, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionBetween(String value1, String value2) {
            addCriterion("trans_description between", value1, value2, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransDescriptionNotBetween(String value1, String value2) {
            addCriterion("trans_description not between", value1, value2, "transDescription");
            return (Criteria) this;
        }

        public Criteria andTransTypeIsNull() {
            addCriterion("trans_type is null");
            return (Criteria) this;
        }

        public Criteria andTransTypeIsNotNull() {
            addCriterion("trans_type is not null");
            return (Criteria) this;
        }

        public Criteria andTransTypeEqualTo(String value) {
            addCriterion("trans_type =", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotEqualTo(String value) {
            addCriterion("trans_type <>", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeGreaterThan(String value) {
            addCriterion("trans_type >", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeGreaterThanOrEqualTo(String value) {
            addCriterion("trans_type >=", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeLessThan(String value) {
            addCriterion("trans_type <", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeLessThanOrEqualTo(String value) {
            addCriterion("trans_type <=", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeLike(String value) {
            addCriterion("trans_type like", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotLike(String value) {
            addCriterion("trans_type not like", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeIn(List<String> values) {
            addCriterion("trans_type in", values, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotIn(List<String> values) {
            addCriterion("trans_type not in", values, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeBetween(String value1, String value2) {
            addCriterion("trans_type between", value1, value2, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotBetween(String value1, String value2) {
            addCriterion("trans_type not between", value1, value2, "transType");
            return (Criteria) this;
        }

        public Criteria andTransPathIsNull() {
            addCriterion("trans_path is null");
            return (Criteria) this;
        }

        public Criteria andTransPathIsNotNull() {
            addCriterion("trans_path is not null");
            return (Criteria) this;
        }

        public Criteria andTransPathEqualTo(String value) {
            addCriterion("trans_path =", value, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransPathNotEqualTo(String value) {
            addCriterion("trans_path <>", value, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransPathGreaterThan(String value) {
            addCriterion("trans_path >", value, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransPathGreaterThanOrEqualTo(String value) {
            addCriterion("trans_path >=", value, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransPathLessThan(String value) {
            addCriterion("trans_path <", value, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransPathLessThanOrEqualTo(String value) {
            addCriterion("trans_path <=", value, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransPathLike(String value) {
            addCriterion("trans_path like", value, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransPathNotLike(String value) {
            addCriterion("trans_path not like", value, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransPathIn(List<String> values) {
            addCriterion("trans_path in", values, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransPathNotIn(List<String> values) {
            addCriterion("trans_path not in", values, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransPathBetween(String value1, String value2) {
            addCriterion("trans_path between", value1, value2, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransPathNotBetween(String value1, String value2) {
            addCriterion("trans_path not between", value1, value2, "transPath");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdIsNull() {
            addCriterion("trans_repository_id is null");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdIsNotNull() {
            addCriterion("trans_repository_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdEqualTo(String value) {
            addCriterion("trans_repository_id =", value, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdNotEqualTo(String value) {
            addCriterion("trans_repository_id <>", value, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdGreaterThan(String value) {
            addCriterion("trans_repository_id >", value, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("trans_repository_id >=", value, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdLessThan(String value) {
            addCriterion("trans_repository_id <", value, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdLessThanOrEqualTo(String value) {
            addCriterion("trans_repository_id <=", value, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdLike(String value) {
            addCriterion("trans_repository_id like", value, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdNotLike(String value) {
            addCriterion("trans_repository_id not like", value, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdIn(List<String> values) {
            addCriterion("trans_repository_id in", values, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdNotIn(List<String> values) {
            addCriterion("trans_repository_id not in", values, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdBetween(String value1, String value2) {
            addCriterion("trans_repository_id between", value1, value2, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransRepositoryIdNotBetween(String value1, String value2) {
            addCriterion("trans_repository_id not between", value1, value2, "transRepositoryId");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelIsNull() {
            addCriterion("trans_log_level is null");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelIsNotNull() {
            addCriterion("trans_log_level is not null");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelEqualTo(String value) {
            addCriterion("trans_log_level =", value, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelNotEqualTo(String value) {
            addCriterion("trans_log_level <>", value, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelGreaterThan(String value) {
            addCriterion("trans_log_level >", value, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelGreaterThanOrEqualTo(String value) {
            addCriterion("trans_log_level >=", value, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelLessThan(String value) {
            addCriterion("trans_log_level <", value, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelLessThanOrEqualTo(String value) {
            addCriterion("trans_log_level <=", value, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelLike(String value) {
            addCriterion("trans_log_level like", value, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelNotLike(String value) {
            addCriterion("trans_log_level not like", value, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelIn(List<String> values) {
            addCriterion("trans_log_level in", values, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelNotIn(List<String> values) {
            addCriterion("trans_log_level not in", values, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelBetween(String value1, String value2) {
            addCriterion("trans_log_level between", value1, value2, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransLogLevelNotBetween(String value1, String value2) {
            addCriterion("trans_log_level not between", value1, value2, "transLogLevel");
            return (Criteria) this;
        }

        public Criteria andTransStatusIsNull() {
            addCriterion("trans_status is null");
            return (Criteria) this;
        }

        public Criteria andTransStatusIsNotNull() {
            addCriterion("trans_status is not null");
            return (Criteria) this;
        }

        public Criteria andTransStatusEqualTo(String value) {
            addCriterion("trans_status =", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotEqualTo(String value) {
            addCriterion("trans_status <>", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusGreaterThan(String value) {
            addCriterion("trans_status >", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusGreaterThanOrEqualTo(String value) {
            addCriterion("trans_status >=", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusLessThan(String value) {
            addCriterion("trans_status <", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusLessThanOrEqualTo(String value) {
            addCriterion("trans_status <=", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusLike(String value) {
            addCriterion("trans_status like", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotLike(String value) {
            addCriterion("trans_status not like", value, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusIn(List<String> values) {
            addCriterion("trans_status in", values, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotIn(List<String> values) {
            addCriterion("trans_status not in", values, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusBetween(String value1, String value2) {
            addCriterion("trans_status between", value1, value2, "transStatus");
            return (Criteria) this;
        }

        public Criteria andTransStatusNotBetween(String value1, String value2) {
            addCriterion("trans_status not between", value1, value2, "transStatus");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(String value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(String value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(String value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(String value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(String value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(String value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLike(String value) {
            addCriterion("is_del like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotLike(String value) {
            addCriterion("is_del not like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<String> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<String> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(String value1, String value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(String value1, String value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledIsNull() {
            addCriterion("is_monitor_enabled is null");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledIsNotNull() {
            addCriterion("is_monitor_enabled is not null");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledEqualTo(String value) {
            addCriterion("is_monitor_enabled =", value, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledNotEqualTo(String value) {
            addCriterion("is_monitor_enabled <>", value, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledGreaterThan(String value) {
            addCriterion("is_monitor_enabled >", value, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledGreaterThanOrEqualTo(String value) {
            addCriterion("is_monitor_enabled >=", value, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledLessThan(String value) {
            addCriterion("is_monitor_enabled <", value, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledLessThanOrEqualTo(String value) {
            addCriterion("is_monitor_enabled <=", value, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledLike(String value) {
            addCriterion("is_monitor_enabled like", value, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledNotLike(String value) {
            addCriterion("is_monitor_enabled not like", value, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledIn(List<String> values) {
            addCriterion("is_monitor_enabled in", values, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledNotIn(List<String> values) {
            addCriterion("is_monitor_enabled not in", values, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledBetween(String value1, String value2) {
            addCriterion("is_monitor_enabled between", value1, value2, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andIsMonitorEnabledNotBetween(String value1, String value2) {
            addCriterion("is_monitor_enabled not between", value1, value2, "isMonitorEnabled");
            return (Criteria) this;
        }

        public Criteria andTplKeyIsNull() {
            addCriterion("tpl_key is null");
            return (Criteria) this;
        }

        public Criteria andTplKeyIsNotNull() {
            addCriterion("tpl_key is not null");
            return (Criteria) this;
        }

        public Criteria andTplKeyEqualTo(String value) {
            addCriterion("tpl_key =", value, "tplKey");
            return (Criteria) this;
        }

        public Criteria andTplKeyNotEqualTo(String value) {
            addCriterion("tpl_key <>", value, "tplKey");
            return (Criteria) this;
        }

        public Criteria andTplKeyGreaterThan(String value) {
            addCriterion("tpl_key >", value, "tplKey");
            return (Criteria) this;
        }

        public Criteria andTplKeyGreaterThanOrEqualTo(String value) {
            addCriterion("tpl_key >=", value, "tplKey");
            return (Criteria) this;
        }

        public Criteria andTplKeyLessThan(String value) {
            addCriterion("tpl_key <", value, "tplKey");
            return (Criteria) this;
        }

        public Criteria andTplKeyLessThanOrEqualTo(String value) {
            addCriterion("tpl_key <=", value, "tplKey");
            return (Criteria) this;
        }

        public Criteria andTplKeyLike(String value) {
            addCriterion("tpl_key like", value, "tplKey");
            return (Criteria) this;
        }

        public Criteria andTplKeyNotLike(String value) {
            addCriterion("tpl_key not like", value, "tplKey");
            return (Criteria) this;
        }

        public Criteria andTplKeyIn(List<String> values) {
            addCriterion("tpl_key in", values, "tplKey");
            return (Criteria) this;
        }

        public Criteria andTplKeyNotIn(List<String> values) {
            addCriterion("tpl_key not in", values, "tplKey");
            return (Criteria) this;
        }

        public Criteria andTplKeyBetween(String value1, String value2) {
            addCriterion("tpl_key between", value1, value2, "tplKey");
            return (Criteria) this;
        }

        public Criteria andTplKeyNotBetween(String value1, String value2) {
            addCriterion("tpl_key not between", value1, value2, "tplKey");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_trans
     *
     * @mbg.generated do_not_delete_during_merge Tue Feb 02 11:07:55 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_trans
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}