package org.yaukie.frame.autocode.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yaukie.frame.autocode.model.XDict;
import org.yaukie.frame.autocode.model.XDictExample;

public interface XDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    long countByExample(XDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    int deleteByExample(XDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    int insert(XDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    int insertSelective(XDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    List<XDict> selectByExample(XDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    XDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") XDict record, @Param("example") XDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    int updateByExample(@Param("record") XDict record, @Param("example") XDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    int updateByPrimaryKeySelective(XDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbg.generated Fri Dec 18 21:13:21 CST 2020
     */
    int updateByPrimaryKey(XDict record);
}