package org.yaukie.frame.autocode.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yaukie.frame.autocode.model.XJob;
import org.yaukie.frame.autocode.model.XJobExample;

public interface XJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    long countByExample(XJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    int deleteByExample(XJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    int insert(XJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    int insertSelective(XJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    List<XJob> selectByExample(XJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    XJob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    int updateByExampleSelective(@Param("record") XJob record, @Param("example") XJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    int updateByExample(@Param("record") XJob record, @Param("example") XJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    int updateByPrimaryKeySelective(XJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job
     *
     * @mbg.generated Tue Feb 02 11:07:55 CST 2021
     */
    int updateByPrimaryKey(XJob record);
}