package org.yaukie.frame.autocode.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yaukie.frame.autocode.model.XLogWarning;
import org.yaukie.frame.autocode.model.XLogWarningExample;

public interface XLogWarningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    long countByExample(XLogWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    int deleteByExample(XLogWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    int insert(XLogWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    int insertSelective(XLogWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    List<XLogWarning> selectByExampleWithBLOBs(XLogWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    List<XLogWarning> selectByExample(XLogWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    XLogWarning selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") XLogWarning record, @Param("example") XLogWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") XLogWarning record, @Param("example") XLogWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    int updateByExample(@Param("record") XLogWarning record, @Param("example") XLogWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    int updateByPrimaryKeySelective(XLogWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(XLogWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log_warning
     *
     * @mbg.generated Mon Jan 18 15:58:33 CST 2021
     */
    int updateByPrimaryKey(XLogWarning record);
}