package org.yaukie.frame.autocode.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yaukie.frame.autocode.model.XLog;
import org.yaukie.frame.autocode.model.XLogExample;

public interface XLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    long countByExample(XLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    int deleteByExample(XLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    int insert(XLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    int insertSelective(XLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    List<XLog> selectByExampleWithBLOBs(XLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    List<XLog> selectByExample(XLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    XLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") XLog record, @Param("example") XLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") XLog record, @Param("example") XLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    int updateByExample(@Param("record") XLog record, @Param("example") XLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    int updateByPrimaryKeySelective(XLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(XLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbg.generated Wed Nov 11 14:28:03 CST 2020
     */
    int updateByPrimaryKey(XLog record);
}