package org.yaukie.frame.autocode.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yaukie.frame.autocode.model.XMonitor;
import org.yaukie.frame.autocode.model.XMonitorExample;

public interface XMonitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    long countByExample(XMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    int deleteByExample(XMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    int insert(XMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    int insertSelective(XMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    List<XMonitor> selectByExample(XMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    XMonitor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") XMonitor record, @Param("example") XMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    int updateByExample(@Param("record") XMonitor record, @Param("example") XMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    int updateByPrimaryKeySelective(XMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_monitor
     *
     * @mbg.generated Wed Jan 20 14:27:32 CST 2021
     */
    int updateByPrimaryKey(XMonitor record);
}