package org.yaukie.frame.autocode.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yaukie.frame.autocode.model.XParams;
import org.yaukie.frame.autocode.model.XParamsExample;

public interface XParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    long countByExample(XParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    int deleteByExample(XParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    int insert(XParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    int insertSelective(XParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    List<XParams> selectByExample(XParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    XParams selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    int updateByExampleSelective(@Param("record") XParams record, @Param("example") XParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    int updateByExample(@Param("record") XParams record, @Param("example") XParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    int updateByPrimaryKeySelective(XParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_params
     *
     * @mbg.generated Thu Jan 21 15:34:52 CST 2021
     */
    int updateByPrimaryKey(XParams record);
}