package org.yaukie.frame.autocode.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yaukie.frame.autocode.model.XTemplate;
import org.yaukie.frame.autocode.model.XTemplateExample;

public interface XTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    long countByExample(XTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    int deleteByExample(XTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    int insert(XTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    int insertSelective(XTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    List<XTemplate> selectByExample(XTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    XTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") XTemplate record, @Param("example") XTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    int updateByExample(@Param("record") XTemplate record, @Param("example") XTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    int updateByPrimaryKeySelective(XTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_template
     *
     * @mbg.generated Thu Feb 18 16:13:14 CST 2021
     */
    int updateByPrimaryKey(XTemplate record);
}